version: "3.8"

services:
  mongo:
    image: mongo:4.4-rc
    container_name: famtube_mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "29170:27017"
    networks:
      - famtube

networks:
  famtube:

volumes:
  mongodb:
    driver: local
